// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/hieronimusbudi/komodo-backend/entity"
	mock "github.com/stretchr/testify/mock"
)

// SellerRepository is an autogenerated mock type for the SellerRepository type
type SellerRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: seller
func (_m *SellerRepository) Delete(seller *entity.Seller) error {
	ret := _m.Called(seller)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Seller) error); ok {
		r0 = rf(seller)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *SellerRepository) GetAll() ([]entity.Seller, error) {
	ret := _m.Called()

	var r0 []entity.Seller
	if rf, ok := ret.Get(0).(func() []entity.Seller); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Seller)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: seller
func (_m *SellerRepository) GetByEmail(seller *entity.Seller) (entity.Seller, error) {
	ret := _m.Called(seller)

	var r0 entity.Seller
	if rf, ok := ret.Get(0).(func(*entity.Seller) entity.Seller); ok {
		r0 = rf(seller)
	} else {
		r0 = ret.Get(0).(entity.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Seller) error); ok {
		r1 = rf(seller)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: seller
func (_m *SellerRepository) GetByID(seller *entity.Seller) error {
	ret := _m.Called(seller)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Seller) error); ok {
		r0 = rf(seller)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: seller
func (_m *SellerRepository) Store(seller *entity.Seller) error {
	ret := _m.Called(seller)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Seller) error); ok {
		r0 = rf(seller)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: seller
func (_m *SellerRepository) Update(seller *entity.Seller) error {
	ret := _m.Called(seller)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Seller) error); ok {
		r0 = rf(seller)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
